on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install Clippy
        run: rustup component add clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
      - name: Formatting Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Lint Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
        